version: "3.9"
services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      NODE_ENV: production

  mobile:
    build:
      context: ./apps/mobile
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./apps/mobile:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
